server:
  port: 31001
spring:
  application:
    name: xc‐service‐manage‐cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms

  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检测模板更新延迟时间，设置为0 表示立即检测，如果时间大于0会有缓存不方便模板测试

#==================== 日志配合·标准  ============================
logging:
  config: classpath:logback-boot.xml